architecture:
  kernels: [100, 25, 11, 3]
  strides: [2, 2, 1, 1]
  dense: [256, 64]
  n_params: 457914

training:
  loss: mae
  input_scale: 0.001
  bins: [50, 240]
  epochs: 25
  n_bins_min: 50
  n_bins_max: 240
